kind: Service
apiVersion: v1
metadata:
  name: transaction-container
  labels:
    app: transaction-container
spec:
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  selector:
    app: transaction-container