kind: Deployment
apiVersion: apps/v1
metadata:
  name: transaction-container
  labels:
    app: transaction-container
spec:
  replicas: 2
  selector:
    matchLabels:
      app: transaction-container
  template:
    metadata:
      labels:
        app: transaction-container
    spec:
      containers:
        - name: transaction-container
          image: default-route-openshift-image-registry.apps.rm1.0a51.p1.openshiftapps.com/stnisrinasalsabila-dev/transaction-app:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
              protocol: TCP
          envFrom:
            - secretRef:
                name: mongo-credentials
          env:
            - name: MONGO_COLLECTION
              value: "trx_collection2"
            - name: PROFILING_URL
              value: "http://profiling-container:8001"